services:
    elephantly.converters:
        class: Elephantly\AmpConverterBundle\Converter\ConverterChain
    
    elephantly.amp_img_converter:
        class: Elephantly\AmpConverterBundle\Converter\Media\AmpImgConverter
        tags:
            - { name: elephanty.amp_converter }
