services:
    elephantly.converters:
        class: Elephantly\AmpConverterBundle\Converter\ConverterChain

    ############################# MEDIA ####################################

    elephantly.amp_img_converter:
        class: Elephantly\AmpConverterBundle\Converter\Media\AmpImgConverter
        tags:
            - { name: elephantly.amp_converter }

    elephantly.amp_brightcove_video_converter:
        class: Elephantly\AmpConverterBundle\Converter\Media\AmpBrightcoveVideoConverter
        tags:
            - { name: elephantly.amp_converter }

    elephantly.amp_video_converter:
        class: Elephantly\AmpConverterBundle\Converter\Media\AmpVideoConverter
        tags:
            - { name: elephantly.amp_converter }

    elephantly.amp_audio_converter:
        class: Elephantly\AmpConverterBundle\Converter\Media\AmpAudioConverter
        tags:
            - { name: elephantly.amp_converter }

    elephantly.amp_youtube_iframe_converter:
        class: Elephantly\AmpConverterBundle\Converter\Media\AmpYoutubeIframeConverter
        tags:
            - { name: elephantly.amp_converter }

    elephantly.amp_dailymotion_iframe_converter:
        class: Elephantly\AmpConverterBundle\Converter\Media\AmpDailymotionIframeConverter
        tags:
            - { name: elephantly.amp_converter }

    elephantly.amp_vimeo_iframe_converter:
        class: Elephantly\AmpConverterBundle\Converter\Media\AmpVimeoIframeConverter
        tags:
            - { name: elephantly.amp_converter }

    elephantly.amp_brightcove_iframe_converter:
        class: Elephantly\AmpConverterBundle\Converter\Media\AmpBrightcoveIframeConverter
        tags:
            - { name: elephantly.amp_converter }

    ############################# SOCIAL ####################################

    elephantly.amp_twitter_converter:
        class: Elephantly\AmpConverterBundle\Converter\Social\AmpTwitterConverter
        tags:
            - { name: elephantly.amp_converter }

    elephantly.amp_instagram_converter:
        class: Elephantly\AmpConverterBundle\Converter\Social\AmpInstagramConverter
        tags:
            - { name: elephantly.amp_converter }

    elephantly.amp_facebook_iframe_converter:
        class: Elephantly\AmpConverterBundle\Converter\Social\AmpFacebookIframeConverter
        tags:
            - { name: elephantly.amp_converter }

    elephantly.amp_facebook_sdk_converter:
        class: Elephantly\AmpConverterBundle\Converter\Social\AmpFacebookSdkConverter
        tags:
            - { name: elephantly.amp_converter }

    elephantly.amp_pinterest_converter:
        class: Elephantly\AmpConverterBundle\Converter\Social\AmpPinterestConverter
        tags:
            - { name: elephantly.amp_converter }

    ############################# LAYOUT ####################################

    elephantly.amp_iframe_converter:
        class: Elephantly\AmpConverterBundle\Converter\Layout\AmpIframeConverter
        tags:
            - { name: elephantly.amp_converter }
