engines:
    phpcodesniffer:
        enabled: true
        config:
            file_extensions: "php,inc,lib"
            standard: "PSR1,PSR2"
    phpmd:
        enabled: true
        config:
            file_extensions: "php,inc,lib"

ratings:
    paths:
    - "**.php"
