dist: trusty
language: php
dist: trusty

notifications:
    email: false

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

addons:
    code_climate:
        repo_token: f247b0d7edc57539b62b4be98713f14f858c80b62df7e894db65e1b4fe705027

before_install:
    - composer install

script:
    - bin/kahlan --clover=clover.xml

after_success:
    - vendor/bin/test-reporter

env:
  CODECOV_TOKEN: 3b8751b7-bba9-4d21-957b-d86af57629fc
